// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleInsuranceProject.Repository;

#nullable disable

namespace VehicleInsuranceProject.Repository.Migrations
{
    [DbContext(typeof(ClaimDbContext))]
    partial class ClaimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleInsuranceProject.Repository.ClaimTable", b =>
                {
                    b.Property<int>("claimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("claimId"));

                    b.Property<int>("claimAmount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("claimDate")
                        .HasColumnType("date");

                    b.Property<string>("claimReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("claimStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("claimId");

                    b.ToTable("Claims");
                });
#pragma warning restore 612, 618
        }
    }
}
